// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadYouTubeAsset(arg1:string,arg2:string):Promise<void>;

export function GetYouTubeInfo(arg1:string):Promise<main.VideoInfo>;

export function Greet(arg1:string):Promise<string>;
