// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadYouTubeAsset(arg1, arg2) {
  return window['go']['main']['App']['DownloadYouTubeAsset'](arg1, arg2);
}

export function GetYouTubeInfo(arg1) {
  return window['go']['main']['App']['GetYouTubeInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
